### PR TITLE
travis: catch up with industrial_ci improvements.

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

Enabling `ccache` should speed up repeated builds.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Guys: :bellhop_bell:

**Comment by gavanderhoorn** [comment]
:bellhop_bell:

**Review by 130s — APPROVED** [review]
> Guys: 🛎

Although I don't think I'm included in the list of guys :)

**Comment by gavanderhoorn** [comment]
@130s wrote:
> > Guys: bellhop_bell
> 
> Although I don't think I'm included in the list of guys :)

unfortunately I need a review from someone with push access to the repository.

Thanks though :)

**Review by Levi-Armstrong — APPROVED** [review]

**Pull request merged**
