### PR TITLE
Fix for issue #48.  Deprecated original logSocketError method

### PR DESCRIPTION
**Pull request by shaun-edwards**

### CODE REVIEW

**Comment by shaun-edwards** [comment]
@gavanderhoorn - please review.

**Comment by gavanderhoorn** [comment]
I think you missed `tcp_client.cpp` and `udp_socket.cpp`.

Also, according to [gcc/onlinedocs/C Extensions - 6.31 - Declaring Attributes of Functions](https://gcc.gnu.org/onlinedocs/gcc/Function-Attributes.html), `deprecated` takes a string argument, which we should perhaps use to point users to the replacement function?

**Comment by shaun-edwards** [comment]
Added deprecated message and squashed commit.  Method is not used in `udp_socket.cpp` (odd, but OK).

**Comment by gavanderhoorn** [comment]
`udp_socket.cpp` has a single call to `logSocketError(..)` in `bool UdpSocket::rawPoll(int timeout, bool & ready, bool & error)` on [line 155](https://github.com/ros-industrial/industrial_core/blob/e00a9f7a9d346450c7255b339fc4863fd59ba5b4/simple_message/src/socket/udp_socket.cpp#L155).

**Comment by shaun-edwards** [comment]
OK...so the problem was that the `indigo-devel` branch was not synced with `hydro-devel`.  This has now been fixed.  All `logSocketError` methods have been updated

**Comment by shaun-edwards** [comment]
@gavanderhoorn, please review (hopefully for the last time).

**Comment by gavanderhoorn** [comment]
lgtm, +1.

**Comment by shaun-edwards** [comment]
@gavanderhoorn, thanks for the review (and your patience).

**Pull request merged**
