### PR TITLE
Fix for issue #127  Uniform sample filter logging is too verbose

### PR DESCRIPTION
**Pull request by mmoerdijk**
Changed all relevant ROS_INFO_STREAM macros to ROS_DEBUG_STREAM macros. Now the filter only outputs the summary at the end.

### CODE REVIEW

**Review by shaun-edwards — APPROVED** [review]
+1

**Comment by shaun-edwards** [comment]
Thanks for the contribution....merging.

**Comment by gavanderhoorn** [comment]
Not sure what happened here @shaun-edwards: the PR is still open, and github tells me that you did a "Merge branch 'indigo-devel' into fix_issue_127" (bc6a130). That is a commit in @mmoerdijk's fork.

**Comment by gavanderhoorn** [comment]
We might want to roll back whatever happened to avoid polluting the history too much.

**Comment by shaun-edwards** [comment]
After I merged #151, it said the branch needed to be updated (it didn't give me a nice green check).  I clicked the "Update branch" button to make sure the build tests passed on the the latest and greatest.  

Oh...it must have pulled in changes from @mmoerdijk's fork?  How weird.  

I'll do a manual merge.  I swear these new github buttons are more trouble than they are worth.

**Comment by shaun-edwards** [comment]
Resubmitted in PR #158

**Pull request closed without merging**
