### PR TITLE
Issue #2 - correctly initialized connected state for udp connections

### PR DESCRIPTION
**Pull request by shaun-edwards**
Also, this fixes the udp unit tests.  I'm not sure why they were broken.

### CODE REVIEW

**Comment by shaun-edwards** [comment]
@jrgnicho, can you review ( I know it's easy ).

**Comment by shaun-edwards** [comment]
@jrgnicho, ping?

**Comment by jrgnicho** [comment]
The only change here sets an inherited bool member to false, should the right fix be to initialize that member to false in the constructor of the base class?

**Comment by shaun-edwards** [comment]
@jrgnicho, all common constructor code moved to base class.

**Comment by shaun-edwards** [comment]
@jrgnicho, ping.

**Comment by jrgnicho** [comment]
+1 for merge

**Pull request merged**
