### PR TITLE
Fix catkin_make on kinetic-devel

### LINKED ISSUE #168: Cannot build kinetic-devel with catkin_make
```
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 8 packages in topological order:
-- ~~  - industrial_core (metapackage)
WARNING: The CMakeLists.txt of the metapackage 'industrial_core' contains non standard content. Use the content of the following file instead: /home/victor/catkin_test/build/catkin_generated/metapackages/industrial_core/CMakeLists.txt
-- ~~  - industrial_deprecated
-- ~~  - industrial_msgs
-- ~~  - simple_message
-- ~~  - industrial_utils
-- ~~  - industrial_robot_client
-- ~~  - industrial_robot_simulator
-- ~~  - industrial_trajectory_filters
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkin_workspace.cmake:95 (message):
  This workspace contains non-catkin packages in it, and catkin cannot build
  a non-homogeneous workspace without isolation.  Try the
  'catkin_make_isolated' command instead.
Call Stack (most recent call first):
  CMakeLists.txt:63 (catkin_workspace)


-- Configuring incomplete, errors occurred!
See also "/home/victor/catkin_test/build/CMakeFiles/CMakeOutput.log".
See also "/home/victor/catkin_test/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

```

### PR DESCRIPTION
**Pull request by VictorLamoine**
Fixes #168

### CODE REVIEW

**Comment by VictorLamoine** [comment]
So we didn't see this issue because Travis CI only builds with `catkin tools`.  I realized this when using `industrial_core` in my GitLab CI: https://gitlab.com/InstitutMaupertuis/fanuc_motion/pipelines/5841251

**Comment by gavanderhoorn** [comment]
Yep. `industrial_ci` doesn't do a build with `catkin_make` (anymore).

@130s, @ipa-mdl.

**Comment by mathias-luedtke** [comment]
> industrial_ci doesn't do a build with catkin_make (anymore).

Yes, this is broken. We could add it again after the refactoring (https://github.com/ros-industrial/industrial_ci/issues/98)

In addition `industrial_ci` disables all metapackages for some reason..

**Review by gavanderhoorn — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Note: this is a partial revert of #161.

**Pull request merged**
