### PR TITLE
Fix issue #13 (field order in docs of RobotStatus msg)

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Opened against `master`, should also be merged with `groovy-devel` and `hydro-devel`.

**Comment by JeremyZoss** [comment]
Fixed in 4405b0d, cb23c64.

**Comment by gavanderhoorn** [comment]
It seems `hydro-devel` is missing this 'fix'. Are you going to merge it in there as well?

**Comment by JeremyZoss** [comment]
Sure.

That branch didn’t exist when I made the first merge (I don’t think).
- Jeremy

**Comment by gavanderhoorn** [comment]
@JeremyZoss: ok, but it will need the fix :)

**Pull request closed without merging**
