### PR TITLE
simple_message: get rid of obsolete gethostbyname

### PR DESCRIPTION
**Pull request by machinekoder**
fix for https://github.com/ros-industrial/industrial_core/issues/108

NOTE: For some reason the run_tests fail on my system, but they also fail without the patch, so I want to see how the CI handles this patch.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Thanks for the PR, and thanks for your WRID18 participation.

Would it be nice to print an info/warning message whenever name resolution doesn't work?

> NOTE: For some reason the run_tests fail on my system, but they also fail without the patch, so I want to see how the CI handles this patch.

seems CI is happy with your changes, I see a checkmark.

**Comment by machinekoder** [comment]
@gavanderhoorn The current behavior implicitly assumes that the `buff` content is either a hostname which can be resolved or an IP address. So printing a warning would cause a warning to be printed whenever one wants to use an explicit IP-address.

So either we change the code to reverse the behavior, first trying to use the buffer contents as an IP-address, then trying to resolve it or it would change the current behavior.

**Review by gavanderhoorn — APPROVED** [review]
Works as described.

Printing warnings or errors when hosts cannot be resolved (or upon any other error) can be added in a later PR.

**Comment by gavanderhoorn** [comment]
Travis failed because of a time-out, not because of something in this PR.

I'll merge.

**Comment by gavanderhoorn** [comment]
Thanks again @machinekoder :+1:

**Pull request merged**
