### PR TITLE
[jade] Update Travis config for Jade

### PR DESCRIPTION
**Pull request by 130s**
Current config in `jade` branch is for Indigo.

### CODE REVIEW

**Comment by 130s** [comment]
Also added is `Kinetic` support as an option.

**Comment by shaun-edwards** [comment]
@130s, I'm interested in your thoughts here.  The`jade` and `indigo` branches are the stable branches of the `indigo-devel` branch.  At some point I expect to create a `jade-devel` for jade specific changes/improvements.  At which point, the `jade` branch will follow that.  My question is whether the each branch should be built for their specific ROS version or if I should build for all versions as suggested in this PR?

**Comment by 130s** [comment]
> My question is whether the each branch should be built for their specific ROS version or if I should build for all versions as suggested in this PR?

I now see the purpose of branches. I updated the commit so that we only check `jade` branch. 

And also I keep kinetic build assuming for the future that this branch may be escalated to `kinetic` branch?

**Comment by shaun-edwards** [comment]
Jade on `shadow-fixed` failed...odd?  I'll have to take a look.

**Comment by 130s** [comment]
@shaun-edwards 

> Jade on shadow-fixed failed...odd? I'll have to take a look.

https://travis-ci.org/ros-industrial/industrial_core/jobs/134473485#L2777

> [industrial_trajectory_filters:cmake]   Could not find a package configuration file provided by
> [industrial_trajectory_filters:cmake]   "moveit_ros_planning" with any of the following names:

This is because `moveit_ros` for jade is [not available in shado-fixed](http://repositories.ros.org/status_page/ros_jade_default.html?q=moveit_ros).

**Comment by shaun-edwards** [comment]
@130s, what's your recommendation here?  Should the `shadow-fixed` builds be allowed to fail and/or should we just accept this as is, knowing what is causing the failure.

**Comment by 130s** [comment]
That's my best guess..(moveit for Jade might still take some time to become available, so does Kinetic). I've updated the commit. We'll see how it works.

**Comment by 130s** [comment]
Test passed.

**Comment by shaun-edwards** [comment]
+1... @130s, thanks for the contribution.

**Pull request merged**
