### PR TITLE
Add travis config as a git submodule from industrial_ci

### PR DESCRIPTION
**Pull request by 130s**

### CODE REVIEW

**Comment by shaun-edwards** [comment]
+1...thanks for the contribution @130s.

@Jmeyer1292, see this PR for how to easily include travis CI.

**Comment by Jmeyer1292** [comment]
@shaun-edwards Forgive me for my ignorance, but I'm not 100% on:
1. What the exact contents of `.travis.yml` should be

**Comment by 130s** [comment]
> ```
> What the exact contents of .travis.yml should be
> ```

I'll update the README in industrial_ci to address the question, but you basically can copy the same file from industrial_core.

**Comment by 130s** [comment]
Looks like mandatory tests that happened on travis by `catkin run_tests` caught some errors in the tests that are defined in some packages. E.g. https://travis-ci.org/ros-industrial/industrial_core/jobs/94386115#L4689

**Pull request merged**
