### PR TITLE
Addresses #141:  dos2unix ran on directory

### PR DESCRIPTION
**Pull request by Jmeyer1292**
This is the result of running the following command on the industrial core library:
`find . -regex '.*\.\(c\|cpp\|h\)$' -print0 | xargs -0 -n 1 -P 4 dos2unix`

Treats  #141

### CODE REVIEW

**Comment by Ridhwanluthra** [comment]
This is a duplicate of PR [#196](https://github.com/ros-industrial/industrial_core/pull/196)

**Comment by Jmeyer1292** [comment]
You should have tagged it on the issue board.

**Comment by Ridhwanluthra** [comment]
When I link an issue it automatically tags it. Also, I don't have the rights to edit the issue board. I had mentioned it in the IRC channel. It's alright.

**Comment by ipa-nhg** [comment]
@Ridhwanluthra if it is duplicate (https://github.com/ros-industrial/industrial_core/pull/196) , should this PR be closed?

**Comment by Ridhwanluthra** [comment]
@ipa-nhg Both the PR are exactly the same.

**Comment by ipa-nhg** [comment]
close! superseded by https://github.com/ros-industrial/industrial_core/pull/196/files

**Pull request closed without merging**
