### PR TITLE
all: update maintainer email addresses.

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

Noticed that Shaun's old SwRI address was still listed in all packages.

### CODE REVIEW

**Comment by robinsonmm** [comment]
Thanks, and we will have the team take a closer look moving forward. Shaun
has expressed interest in continuing to maintain Motoman related repos, but
even those should be updated to his current email address.

MR

**Comment by gavanderhoorn** [comment]
Can we please get this merged first? I'd like to not have invalid email addresses in package manifests, even if the listed address is not the preferred maintainer any longer.

We can then start the discussion on who should be listed where.

**Comment by gavanderhoorn** [comment]
To move forward, I need a review from at least one other maintainer with write access.

**Comment by gavanderhoorn** [comment]
:bellhop_bell: @Levi-Armstrong or @shaun-edwards.

**Review by jrgnicho — APPROVED** [review]

**Comment by jrgnicho** [comment]
@gavanderhoorn thanks for the update

**Pull request merged**
