### PR TITLE
update and unify Readme files

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Review by AustinDeric — COMMENTED** [review]
~looks great to me! +1~

**Review by AustinDeric — APPROVED** [review]
looks great to me! +1
image

**Comment by AustinDeric** [comment]
maybe add some info about the docker image thats available for this repo?

## Docker
```
docker run -it rosindustrial/core:kinetic rosmsg show industrial_msgs/RobotStatus
```

**Review by jrgnicho — APPROVED** [review]
@ipa-nhg thanks for the contribution.

**Pull request merged**
