### PR TITLE
simple_message: build unit tests conditionally

### PR DESCRIPTION
**Pull request by rojkov**
This is indigo-devel version of #182

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Thanks for the PRs.

Nice of you to make the effort, but there was no need to submit `indigo-devel` versions of it: we'll cherry-pick or PR ourselves from `kinetic-devel` when/if necessary.

**Comment by shaun-edwards** [comment]
@rojkov, do you need this in a specific version?

**Comment by rojkov** [comment]
@shaun-edwards I'm fine with any version this patch is going to end up in. Currently the patch is a part of the simple-message 0.4.3 recipe in meta-ros (OpenEmbedded meta layer [1])

[1] https://github.com/bmwcarit/meta-ros

**Review by shaun-edwards — APPROVED** [review]

**Comment by shaun-edwards** [comment]
@rojkov, thanks for the contribution.

**Pull request merged**
