### PR TITLE
Update the libraries install tags - follow the official documentation

### PR DESCRIPTION
**Pull request by ipa-nhg**

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
This is not really needed.
Please include the dummy lib as well.

**Comment by mathias-luedtke** [comment]
It might be even better to get rid of these dummy libs at all ;)

**Comment by gavanderhoorn** [comment]
Thanks for the PR @ipa-nhg.

re: `dummy_lib`: that is already installed [here](https://github.com/ros-industrial/industrial_core/blob/e3fac7f5018c6c8db9e859e89947e2b52159e0da/simple_message/CMakeLists.txt#L93). Could you please remove it from the lines you updated *or* remove the `install(..)` statement that installs the dummy lib?

**Comment by ipa-nhg** [comment]
@gavanderhoorn thanks for the review, just remove this commit https://github.com/ros-industrial/industrial_core/pull/193/commits/04ee84e384d7fb20df3701a351baf87124cffa04 should be ok. I will rebase and drop it

**Comment by gavanderhoorn** [comment]
You just added 66e24525, was that intentional?

**Comment by ipa-nhg** [comment]
@gavanderhoorn no, I removed a previous commit. Probably the branch was updated (using the web interface "update branch" button yesterday??)....

**Comment by gavanderhoorn** [comment]
I don't know, I don't see any updates in the gh ui.

It would be good if we can keep these things separate. Could you drop 66e2452 from your `LibInstallTags` branch?

**Comment by ipa-nhg** [comment]
@gavanderhoorn Yep! done!

**Review by gavanderhoorn — APPROVED** [review]
Looks good.

**Comment by gavanderhoorn** [comment]
Thanks again @ipa-nhg :+1:

**Pull request merged**
